<?php

/**
 * Допустимые классы Font Awesome (solid) для иконки статуса занятия.
 * Должны совпадать с подключаемой в админке версией FA.
 */
return [
    'fa-solid fa-calendar-plus',
    'fa-solid fa-calendar-check',
    'fa-solid fa-calendar-day',
    'fa-solid fa-calendar-xmark',
    'fa-solid fa-circle-check',
    'fa-solid fa-circle-xmark',
    'fa-solid fa-ban',
    'fa-solid fa-snowflake',
    'fa-solid fa-star',
    'fa-solid fa-icons',
    'fa-solid fa-check',
    'fa-solid fa-xmark',
    'fa-solid fa-clock',
    'fa-solid fa-hourglass-half',
    'fa-solid fa-user-check',
    'fa-solid fa-user-xmark',
    'fa-solid fa-user-slash',
    'fa-solid fa-house',
    'fa-solid fa-bell',
    'fa-solid fa-exclamation',
    'fa-solid fa-triangle-exclamation',
    'fa-solid fa-circle-info',
    'fa-solid fa-pause',
    'fa-solid fa-play',
    'fa-solid fa-stop',
    'fa-solid fa-book',
    'fa-solid fa-chalkboard-user',
    'fa-solid fa-graduation-cap',
    'fa-solid fa-person-running',
    'fa-solid fa-heart',
    'fa-solid fa-thumbs-up',
    'fa-solid fa-thumbs-down',
    'fa-solid fa-minus',
    'fa-solid fa-plus',
    'fa-solid fa-question',
    'fa-solid fa-shuffle',
    'fa-solid fa-repeat',
    'fa-solid fa-arrow-right',
    'fa-solid fa-arrow-left',
    'fa-solid fa-moon',
    'fa-solid fa-sun',
    'fa-solid fa-cloud',
    'fa-solid fa-bolt',
    'fa-solid fa-fire',
    'fa-solid fa-droplet',
];
