<?php

return [
    'roles' => [
        'user' => [
            'dashboard.view',
            'myPayments.view',
            'myGroup.view',
            'account.user.view',
            'account.partner.view',
            'account.partner.update',
            'account.documents.view',
            'account.user.birthdate.update',
            'account.user.email.update',
            'account.user.phone.update',
            'paying.classes',
            'payment.clubfee',
        ],
        'admin' => [
            'dashboard.view',
            'reports.view',
            'setPrices.view',
            'schedule.view',
            'users.view',
            'groups.view',
            'contracts.view',
            'settings.view',
            'settings.roles.view',
            'settings.paymentSystems.view',
            'account.user.view',
            'account.partner.view',
            'account.partner.update',
            'account.documents.view',
            'servicePayments.view',
            'partnerWallet.view',
            'blog.view',
            'account.user.name.update',
            'account.user.birthdate.update',
            'account.user.team.update',
            'account.user.startDate.update',
            'account.user.email.update',
            'account.user.phone.update',
            'users.name.update',
            'users.birthdate.update',
            'users.group.update',
            'users.startDate.update',
            'users.email.update',
            'users.activity.update',
            'users.role.update',
            'users.password.update',
            'users.phone.update',
            'payment.clubfee',
            // 'change_history',
            // 'manage_roles',
            // 'manage.payment.method.tbank',
        ],
    ],
];

