<?php

return [
    'roles' => [
        'user' => [
            'dashboard.view',
            'myPayments.view',
            'myGroup.view',
            'account.user.view',
            'account.partner.view',
            'account.partner.update',
            'account.documents.view',
            'account.user.birthdate.update',
            'changing_user_email',
            'account.user.phone.update',
            'paying_classes',
            'payment_clubfee',
        ],
        'admin' => [
            'dashboard.view',
            'reports.view',
            'setPrices.view',
            'schedule.view',
            'users.view',
            'groups.view',
            'contracts.view',
            'settings.view',
            'settings.roles.view',
            'settings.paymentSystems.view',
            'account.user.view',
            'account.partner.view',
            'account.partner.update',
            'account.documents.view',
            'servicePayments.view',
            'partnerWallet.view',
            'blog.view',
            'name_editing',
            'account.user.birthdate.update',
            'changing_your_group',
            'account.user.startDate.update',
            'changing_user_email',
            'account.user.phone.update',
            'users.name.update',
            'users.birthdate.update',
            'users.group.update',
            'users.startDate.update',
            'users.email.update',
            'users.activity.update',
            'users.role.update',
            'users.password.update',
            'users.phone.update',
            'payment_clubfee',
            'change_history',
            'manage_roles',
            // 'manage_payment_method_T-Bank',
        ],
    ],
];

